kind: Secret
metadata:
  name: backend-secrets
  namespace: staging
type: Opaque
stringData:
  DATABASE_HOST: "<DB_HOST>"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "phongtro_db"
  DATABASE_USER: "dbadmin"
  DATABASE_PASSWORD: "<DB_PASSWORD>"

  JWT_SECRET: "<RANDOM_SECRET_KEY>"

  AWS_ACCESS_KEY_ID: "<AWS_KEY>"
  AWS_SECRET_ACCESS_KEY: "<AWS_SECRET>"
